#!/bin/bash

folder=$1

[[ -z $folder ]] && folder=`go list ./... | grep -v 'examples'`

while true
do
  #make test
  go test -shuffle=on -count=1 -coverprofile=coverage.out ${folder[@]}
  coverage=$(go tool cover -func=coverage.out | tail -1 | awk '{ print $3; }')
  [[ $coverage == "100.0%" ]] || exit 0
done

