#!/bin/zsh

image_name=$(docker images --format json | jq -r '.Repository' | grep "^ubuntu-go$")
[[ $image_name == "ubuntu-go" ]] || docker build -f ./scripts/ubuntu.Dockerfile -t ubuntu-go .

docker run -it --rm \
  -v "$PWD":/work \
  -w /work \
  ubuntu-go bash
