#!/bin/bash

# gives more similar behavior to github actions

test_command='
go test -race -coverprofile=coverage.out `go list ./... | grep -v "examples"`
go tool cover -html=coverage.out -o coverage.html
'
docker run --rm \
  -v "$PWD":/work -w /work \
  golang:1.25 \
  sh -c "${test_command}"
