on:
  push:
    #branches:
    #  - main
  schedule:
    - cron: '0 9 * * 1'  # weekly, Mondays 09:00 UTC

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ossf/scorecard-action@latest
        with:
          publish_results: true
